/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.views;

import app.controller.HomeController;
import javax.swing.DefaultListModel;
import java.awt.Color;

/**
 *
 * @author miguelvazquez
 */
public class Home extends javax.swing.JFrame {
    
    private DefaultListModel listModel = new DefaultListModel();
    private String defaultTitleText = "Que hay de nuevo...";
    private HomeController homeController = new HomeController();

    /**
     * Creates new form HomeJFrame
     */
    public Home() {
        initComponents();
        jListTask.setModel(listModel);
        jListTask.setForeground(Color.BLACK);
        jListTask.setSelectionBackground(new Color(187, 222, 251));
        jListTask.setFixedCellHeight(30);
        InputTitle.setText(defaultTitleText);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        InputTitle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTask = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(187, 222, 251));

        InputTitle.setBackground(new java.awt.Color(187, 222, 251));
        InputTitle.setText("jTextField1");
        InputTitle.setBorder(null);
        InputTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InputTitleMousePressed(evt);
            }
        });
        InputTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InputTitleKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("+");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jListTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTaskMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListTaskMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jListTask);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputTitleMousePressed
        // TODO add your handling code here:
        if(InputTitle.getText().equals(defaultTitleText)){
            InputTitle.setText("");
        }
    }//GEN-LAST:event_InputTitleMousePressed

    private void InputTitleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputTitleKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10 && !InputTitle.getText().isEmpty() && !InputTitle.getText().equals(defaultTitleText)){
            String title = InputTitle.getText().trim();
            homeController.addInitTask(title);
            listModel.addElement(title);
            InputTitle.setText(defaultTitleText);
            InputTitle.selectAll();
        }
    }//GEN-LAST:event_InputTitleKeyPressed

    private void jListTaskMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTaskMousePressed
        // TODO add your handling code here:
        if(InputTitle.getText().equals("")){
            InputTitle.setText(defaultTitleText);
        }
    }//GEN-LAST:event_jListTaskMousePressed

    private void jListTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTaskMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int index = jListTask.locationToIndex(evt.getPoint());
            
            TaskDetail taskDetail = new TaskDetail();
            taskDetail.setHomeController(homeController);
            taskDetail.setIndexItem(index);
            taskDetail.setListModel(listModel);
            taskDetail.showData();
            taskDetail.setVisible(true);
        }
    }//GEN-LAST:event_jListTaskMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListTask;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
